# Generated by Django 5.2.2 on 2025-06-09 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Donation_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donordetails1',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
